unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g history-limit 50000
set -g mouse on
set -g set-titles on
set -g set-titles-string '#S:#W'
set -ga terminal-overrides ',xterm*:smcup@:rmcup@'

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

